export const FLAGS = {
  Bhutan: 'bt',
  ['Brunei Darussalam']: 'bn',
  Cambodia: 'kh',
  Indonesia: 'id',
  Kazakhstan: 'kz',
  ['Kyrgyz Republic']: 'kg',
  ['Lao PDR']: 'la',
  Malaysia: 'my',
  Mongolia: 'mn',
  Myanmar: 'mm',
  Philippines: 'ph',
  ['Republic of Korea']: 'kr',
  Singapore: 'sg',
  Thailand: 'th',
  ['Timor-Leste']: 'tl',
  ['Viet Nam']: 'vn',
};
