name: Cypress Tests

on:
  push:
    paths:
      - 'client/**'
      - '.github/workflows/testing-e2e.yml'

  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ${{github.workspace}}/client
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18.17
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install --immutable

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: yarn build
          start: yarn start
          command: "yarn test:e2e"
          working-directory: client
          install: false
        env:
          NEXT_PUBLIC_MAPBOX_API_TOKEN: ${{ secrets.NEXT_PUBLIC_MAPBOX_API_TOKEN }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NODE_ENV: production
