name: Cypress Tests

on:
  push:
    paths:
      - 'client/**'
      - '.github/workflows/testing-e2e.yml'

  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: yarn build
          start: yarn start
          command: "yarn cypress:open"
